Fix ValueError in t_tide.py when jref is empty line 430
Fixes this error:
ValueError: The truth value of an empty array is ambiguous. Use `array.size > 0` to check that an array is not empty.
Occurs because of if "ii:"

Prevents crashes when jref is empty.